class Resistor {
    r: number = 0;
    constructor(r: number) {
        this.r = r;
    }
    getCurrent(u: number): number {
        return u / this.r;
    }
    getPotential(current: number): number {
        return current * this.r;
    }
    getPower(u: number): number {
        return u * this.getCurrent(u);
    }
    getResistance(): number {
        return this.r;
    }
}

class SeriesCircuit {
    resistors: Resistor[] = []
    push(r: Resistor) {
        this.resistors.push(r);
    }
    getTotalResistance() {
        let sum: number = 0;
        this.resistors.forEach((r: Resistor) => { sum += r.getResistance() });
        return sum;
    }
    getCurrent(u: number) {
        return u / this.getTotalResistance();
    }
    getBiggestResistorPower(u: number) {
        if (this.resistors.length == 0) { return 0; }
        let current: number = this.getCurrent(u);
        let biggestPower: number = this.resistors[0].getPower(this.resistors[0].getPotential(current));
        for (let i = 1; i < this.resistors.length; i++) {
            let power: number = this.resistors[i].getPower(this.resistors[i].getPotential(current));
            if (power > biggestPower) { biggestPower = power; }
        }
        return biggestPower;
    }
    getTotalPower(u: number) {
        let current = this.getCurrent(u);
        let totalPower = 0;
        this.resistors.forEach(r => {
            totalPower += r.getPower(r.getPotential(current));
        });
        return totalPower;
    }
}

let sc1: SeriesCircuit = new SeriesCircuit();
sc1.push(new Resistor(220));
sc1.push(new Resistor(220));
sc1.push(new Resistor(110));

let sc2: SeriesCircuit = new SeriesCircuit();
sc2.push(new Resistor(100));
sc2.push(new Resistor(200));
sc2.push(new Resistor(300));

let largestResistance: number = 0;
sc1.resistors.forEach((r: Resistor) => {
    if (r.getResistance() > largestResistance) {
        largestResistance = r.getResistance();
    }
});
console.log("The largest resistance in sc1 is: " + largestResistance);

largestResistance = 0;
sc2.resistors.forEach((r: Resistor) => {
    if (r.getResistance() > largestResistance) {
        largestResistance = r.getResistance();
    }
});
console.log("The largest resistance in sc2 is: " + largestResistance);

let current = sc1.getCurrent(5);
let largestVoltage: number = 0;
sc1.resistors.forEach((r: Resistor) => {
    let voltage = r.getPotential(current);
    if (voltage > largestVoltage) {
        largestVoltage = voltage;
    }
});
console.log("The largest voltage in sc1 is: " + largestVoltage);

current = sc2.getCurrent(5);
largestVoltage = 0;
sc2.resistors.forEach((r: Resistor) => {
    let voltage = r.getPotential(current);
    if (voltage > largestVoltage) {
        largestVoltage = voltage;
    }
});
console.log("The largest voltage in sc2 is: " + largestVoltage);

// Output the largest power generated by one of the resistors in the series circuit with 5V total voltage
current = sc1.getCurrent(5);
let largestPower: number = 0;
sc1.resistors.forEach((r: Resistor) => {
    let power = r.getPower(r.getPotential(current));
    if (power > largestPower) {
        largestPower = power;
    }
});
console.log("The largest power in sc1 is: " + largestPower);

current = sc2.getCurrent(5);
largestPower = 0;
sc2.resistors.forEach((r: Resistor) => {
    let power = r.getPower(r.getPotential(current));
    if (power > largestPower) {
        largestPower = power;
    }
});
console.log("The largest power in sc2 is: " + largestPower);
